[tools]
"aqua:rossmacarthur/sheldon" = "0.8.5"
bat = "0.26.1"
bitwarden = "2026.1.0"
cargo-make = "0.37.24"
"cargo:jj-starship" = "0.7.0"
"cargo:zabrze" = "0.7.2"
eza = "0.23.4"
fd = "10.3.0"
fzf = "0.68.0"
gh = "2.87.2"
ghq = "1.9.4"
go = "1.26.0"
"go:github.com/Warashi/cage" = "0.1.13"
jj = "0.38.0"
node = "24.13.1"
"npm:@google/gemini-cli" = "0.29.5"
"npm:@sasazame/ccresume" = "1.0.0"
"npm:ccusage" = "18.0.5"
"npm:difit" = "3.1.10"
ripgrep = "15.1.0"
starship = "1.24.2"
terraform = "1.14.5"
usage = "2.18.0"
uv = "0.10.4"
yq = "4.52.4"
zellij = "0.43.1"

[hooks]
postinstall = "$MISE_CONFIG_HOME/hooks/postinstall.sh"
# Set GIT_DIR in jj repo
cd = '''
unset GIT_DIR
if jj root > /dev/null 2>&1; then
  export GIT_DIR=$(jj git root)
fi
'''

[settings]
idiomatic_version_file_enable_tools = ["java"]
experimental = true
