[tools]
claude = "latest"
deno = "latest"
go = "latest"
"go:github.com/Warashi/cage" = "latest"
node = "24"
"npm:@google/gemini-cli" = "latest"
"npm:@sasazame/ccresume" = "latest"
"npm:ccusage" = "latest"
"npm:difit" = "latest"
pipx = "latest"
"pipx:httpie" = "latest"
python = "latest"
rust = "latest"
terraform = "latest"
usage = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["java"]
experimental = true
